version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: formularioport
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: contacto  
      MYSQL_USER: ismael
      MYSQL_PASSWORD: 0112
    ports:
      - "6001:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mariadb_data:
    driver: local
